"""Mock paper records covering realistic biomedical ML scenarios.

These are illustrative examples — not real papers.
Replace with real data by populating PaperRecord objects or loading from JSON/CSV.
"""

from src.schemas import PaperRecord

MOCK_PAPERS: list[PaperRecord] = [
    # -----------------------------------------------------------------------
    # Group A: Sleep staging on SHHS, 5-class, subject-wise, macro-F1
    # -----------------------------------------------------------------------
    PaperRecord(
        title="SleepTransformer: Sequence-to-Sequence Sleep Staging via Transformers",
        year=2022,
        paper_url="https://example.com/sleeptransformer",
        datasets_used=["SHHS"],
        target_dataset_only=True,
        task="Sleep Staging",
        label_granularity="5-class (W/N1/N2/N3/REM)",
        train_split="70%",
        val_split="10%",
        test_split="20%",
        cross_validation="20-fold subject-wise",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.3–35 Hz", "30s epoch", "z-score normalization"],
        modalities=["EEG", "EOG"],
        model_name="SleepTransformer",
        models_compared=["DeepSleepNet", "SeqSleepNet", "U-Time"],
        metric_name="F1-macro",
        metric_value=0.793,
        result_scope="test",
        notes="Uses full-night PSG sequences; context window of 25 epochs.",
        confidence="high",
        source_snippet="Overall MF1 of 79.3% on SHHS holdout subjects.",
    ),
    PaperRecord(
        title="U-Time: A Fully Convolutional Network for Time Series Segmentation",
        year=2019,
        paper_url="https://example.com/u-time",
        datasets_used=["SHHS"],
        target_dataset_only=True,
        task="Sleep Staging",
        label_granularity="5-class (W/N1/N2/N3/REM)",
        train_split="70%",
        val_split="10%",
        test_split="20%",
        cross_validation="20-fold subject-wise",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.3–35 Hz", "30s epoch"],
        modalities=["EEG", "EOG", "EMG"],
        model_name="U-Time",
        models_compared=["DeepSleepNet"],
        metric_name="F1-macro",
        metric_value=0.771,
        result_scope="test",
        notes="Fully convolutional; treats staging as dense prediction over time.",
        confidence="high",
        source_snippet="MF1=77.1% averaged across SHHS test subjects.",
    ),
    PaperRecord(
        title="DeepSleepNet: A Model for Automatic Sleep Stage Scoring",
        year=2017,
        paper_url="https://example.com/deepsleepnet",
        datasets_used=["SHHS", "Sleep-EDF"],
        target_dataset_only=False,
        task="Sleep Staging",
        label_granularity="5-class (W/N1/N2/N3/REM)",
        train_split="UNKNOWN",
        val_split="UNKNOWN",
        test_split="UNKNOWN",
        cross_validation="20-fold subject-wise",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.3–35 Hz", "30s epoch"],
        modalities=["EEG"],
        model_name="DeepSleepNet",
        models_compared=["CNN baseline", "LSTM baseline"],
        metric_name="F1-macro",
        metric_value=0.758,
        result_scope="test",
        notes="Pretrained on Sleep-EDF then fine-tuned on SHHS — numbers may reflect cross-dataset generalization.",
        confidence="medium",
        source_snippet="Overall F1 of 75.8% reported in Table 3.",
    ),

    # -----------------------------------------------------------------------
    # Group B: Sleep staging on Sleep-EDF-20, 5-class, subject-wise, accuracy
    # (different metric from Group A — not directly comparable)
    # -----------------------------------------------------------------------
    PaperRecord(
        title="EEG-Conformer: Convolutional Transformer for EEG Decoding",
        year=2023,
        paper_url="https://example.com/eeg-conformer",
        datasets_used=["Sleep-EDF-20"],
        target_dataset_only=True,
        task="Sleep Staging",
        label_granularity="5-class (W/N1/N2/N3/REM)",
        train_split="UNKNOWN",
        val_split="UNKNOWN",
        test_split="UNKNOWN",
        cross_validation="10-fold subject-wise",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.5–30 Hz", "30s epoch", "resampled to 100 Hz"],
        modalities=["EEG"],
        model_name="EEG-Conformer",
        models_compared=["AttnSleep", "XSleepNet", "MSTGNN"],
        metric_name="Accuracy",
        metric_value=0.843,
        result_scope="test",
        notes="Single-channel Fpz-Cz; 10-fold cross-validation over 20 subjects.",
        confidence="high",
        source_snippet="Accuracy 84.3% (±1.2) on Sleep-EDF-20 Fpz-Cz channel.",
    ),
    PaperRecord(
        title="AttnSleep: An Attention-Based Deep Learning Approach for Sleep Stage Detection",
        year=2021,
        paper_url="https://example.com/attnsleep",
        datasets_used=["Sleep-EDF-20"],
        target_dataset_only=True,
        task="Sleep Staging",
        label_granularity="5-class (W/N1/N2/N3/REM)",
        train_split="UNKNOWN",
        val_split="UNKNOWN",
        test_split="UNKNOWN",
        cross_validation="10-fold subject-wise",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.5–40 Hz", "30s epoch"],
        modalities=["EEG"],
        model_name="AttnSleep",
        models_compared=["DeepSleepNet", "SeqSleepNet"],
        metric_name="Accuracy",
        metric_value=0.831,
        result_scope="test",
        notes="Multi-head attention over temporal features; single-channel Fpz-Cz.",
        confidence="high",
        source_snippet="Overall accuracy 83.1% on Sleep-EDF-20.",
    ),

    # -----------------------------------------------------------------------
    # Partial: Sleep staging with random-window split (not subject-wise)
    # -----------------------------------------------------------------------
    PaperRecord(
        title="SimpleSleep: A Lightweight CNN Baseline for Sleep Staging",
        year=2020,
        paper_url="https://example.com/simplesleep",
        datasets_used=["Sleep-EDF-20"],
        target_dataset_only=True,
        task="Sleep Staging",
        label_granularity="5-class (W/N1/N2/N3/REM)",
        train_split="80%",
        val_split="UNKNOWN",
        test_split="20%",
        cross_validation="UNKNOWN",
        split_type="random-window",
        preprocessing_steps=["bandpass 0.5–30 Hz", "30s epoch"],
        modalities=["EEG"],
        model_name="SimpleSleep-CNN",
        models_compared=[],
        metric_name="Accuracy",
        metric_value=0.872,
        result_scope="test",
        notes="CAUTION: random 80/20 split of windows, NOT subject-wise. "
              "Inflated accuracy likely due to data leakage across subjects.",
        confidence="medium",
        source_snippet="Accuracy 87.2% on held-out windows (random split).",
    ),

    # -----------------------------------------------------------------------
    # Group C: ECG arrhythmia classification, MIT-BIH, 5-class, accuracy
    # -----------------------------------------------------------------------
    PaperRecord(
        title="ECG-Net: A Deep Neural Network for Arrhythmia Classification",
        year=2021,
        paper_url="https://example.com/ecg-net",
        datasets_used=["MIT-BIH Arrhythmia Database"],
        target_dataset_only=True,
        task="ECG Arrhythmia",
        label_granularity="5-class (AAMI: N/S/V/F/Q)",
        train_split="70%",
        val_split="10%",
        test_split="20%",
        cross_validation="UNKNOWN",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.5–40 Hz", "R-peak detection", "beat segmentation"],
        modalities=["ECG"],
        model_name="ECG-Net (1D-CNN + BiLSTM)",
        models_compared=["ResNet-1D", "XGBoost"],
        metric_name="Accuracy",
        metric_value=0.986,
        result_scope="test",
        notes="Per-beat classification; class imbalance handled via oversampling.",
        confidence="high",
        source_snippet="Overall accuracy 98.6% on MIT-BIH held-out records.",
    ),
    PaperRecord(
        title="Transformer-ECG: Self-Attention for Heartbeat Classification",
        year=2022,
        paper_url="https://example.com/transformer-ecg",
        datasets_used=["MIT-BIH Arrhythmia Database"],
        target_dataset_only=True,
        task="ECG Arrhythmia",
        label_granularity="5-class (AAMI: N/S/V/F/Q)",
        train_split="70%",
        val_split="10%",
        test_split="20%",
        cross_validation="UNKNOWN",
        split_type="subject-wise",
        preprocessing_steps=["bandpass 0.5–40 Hz", "R-peak detection", "beat segmentation", "resampled to 360 Hz"],
        modalities=["ECG"],
        model_name="Transformer-ECG",
        models_compared=["ECG-Net", "ResNet-1D"],
        metric_name="Accuracy",
        metric_value=0.989,
        result_scope="test",
        notes="Uses the DS2 recommended inter-patient split for MIT-BIH.",
        confidence="high",
        source_snippet="Accuracy 98.9% on MIT-BIH using recommended inter-patient evaluation.",
    ),

    # -----------------------------------------------------------------------
    # Not comparable: missing task/metric
    # -----------------------------------------------------------------------
    PaperRecord(
        title="PhysioSSL: Self-Supervised Learning on Physiological Signals",
        year=2023,
        paper_url="https://example.com/physiossL",
        datasets_used=["SHHS", "MESA", "Sleep-EDF-20"],
        target_dataset_only=False,
        task="UNKNOWN",
        label_granularity="UNKNOWN",
        train_split="UNKNOWN",
        val_split="UNKNOWN",
        test_split="UNKNOWN",
        cross_validation="UNKNOWN",
        split_type="UNKNOWN",
        preprocessing_steps=["bandpass 0.3–35 Hz"],
        modalities=["EEG", "ECG", "EOG"],
        model_name="PhysioSSL (contrastive)",
        models_compared=[],
        metric_name="UNKNOWN",
        metric_value="UNKNOWN",
        result_scope="unknown",
        notes="Pretraining paper — no downstream benchmark numbers extracted yet. "
              "Needs follow-up reading.",
        confidence="low",
        source_snippet="",
    ),
]
